# Generated by Django 5.0.4 on 2024-04-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('choose_your_course', models.CharField(choices=[('PHP Full Stack', 'PHP Full Stack'), ('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('Software Testing Advanced', 'Software Testing Advanced'), ('Software Testing Manual', 'Software Testing Manual')], max_length=50)),
                ('mobile_number', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('guardians_mobile', models.IntegerField(max_length=100)),
                ('training_mode', models.CharField(choices=[('Live online', 'Live online'), ('Classroom', 'Classroom')], max_length=20)),
                ('location', models.CharField(choices=[('Technopark TVM', 'Technopark TVM'), ('Thampanoor TVM', 'Thampanoor TVM'), ('Kochi', 'Kochi'), ('Nagercoil', 'Nagercoil'), ('Online', 'Online')], max_length=20)),
            ],
        ),
    ]
