# Generated by Django 5.0.4 on 2024-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_registration_choose_your_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='guardians_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='guardians_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='pin_zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='preferred_training_timings',
            field=models.CharField(choices=[('time1', 'Between 7am - 10am'), ('time2', 'Between 9am - 1pm'), ('time3', 'Between 1pm - 6pm'), ('time4', 'Between 6pm - 10pm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='choose_your_course',
            field=models.CharField(choices=[('PHP Full Stack', 'PHP Full Stack'), ('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('Software Testing Advanced', 'Software Testing Advanced'), ('Software Testing Manual', 'Software Testing Manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(choices=[('Technopark TVM', 'Technopark TVM'), ('Thampanoor TVM', 'Thampanoor TVM'), ('Kochi', 'Kochi'), ('Nagercoil', 'Nagercoil'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='training_mode',
            field=models.CharField(choices=[('Live online', 'Live online'), ('Classroom', 'Classroom')], max_length=20),
        ),
    ]
