# Generated by Django 5.0.4 on 2024-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_registration_address_registration_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='preferred_training_timings',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
