# Generated by Django 5.0.4 on 2024-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_registration_preferred_training_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
