# Generated by Django 5.0.4 on 2024-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_registration_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('new', models.CharField(max_length=100)),
                ('confirm', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
    ]
