# Generated by Django 5.0.4 on 2024-05-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_details_confirm_remove_details_new_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
