# Generated by Django 5.0.4 on 2024-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=255)),
            ],
        ),
    ]
