# Generated by Django 5.0.4 on 2024-06-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_selectedcourse_delete_selectedcourses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
