# Generated by Django 5.0.4 on 2024-06-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_selectedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
