# Generated by Django 5.0.4 on 2024-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('upload_avatar', models.FileField(upload_to='user_avatar')),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('guardians_mobile', models.IntegerField()),
                ('training_mode', models.CharField(choices=[('Live online', 'Live online'), ('Classroom', 'Classroom')], max_length=20)),
                ('location', models.CharField(choices=[('Technopark TVM', 'Technopark TVM'), ('Thampanoor TVM', 'Thampanoor TVM'), ('Kochi', 'Kochi'), ('Nagercoil', 'Nagercoil'), ('Online', 'Online')], max_length=20)),
                ('guardians_name', models.CharField(blank=True, max_length=100)),
                ('guardians_occupation', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.CharField(choices=[('cycling', 'cycling'), ('gardening', 'gardening'), ('cooking', 'cooking'), ('knitting', 'knitting')], max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pin_zip_code', models.IntegerField(null=True)),
            ],
        ),
    ]
