# Generated by Django 5.0.4 on 2024-06-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_selectedcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcourse',
            name='user_id',
        ),
    ]
