# Generated by Django 5.0.4 on 2024-06-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_selectedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
