# Generated by Django 5.0.4 on 2024-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_selectedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_names', models.CharField(max_length=255)),
            ],
        ),
    ]
