# Generated by Django 5.0.4 on 2024-06-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_selectedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
