# Generated by Django 5.0.4 on 2024-06-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_selectedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
