# Generated by Django 5.0.4 on 2024-06-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_course_fees_selectedcourses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcourses',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='selectedcourses',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='SelectedCourses',
        ),
    ]
