# Generated by Django 5.0.4 on 2024-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_course_selectedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='hobbies',
            field=models.TextField(),
        ),
    ]
